name: Certbot website CI
on:
  push:
  pull_request:
  schedule:
    # Run at 4pm UTC or 9am PST
    - cron: "0 16 * * *"
env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  NODE_ENV: production
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install OS packages
        run: |
          sudo apt-get update
          sudo apt-get install gsfonts imagemagick latexmk texlive texlive-latex-extra -y
      - uses: ruby/setup-ruby@v1
        with:
          bundler: "none"
          ruby-version: 2.6.3
      - name: Install Ruby packages
        run: gem install jekyll html-proofer
      - uses: actions/setup-node@v2
        with:
          node-version: 8.12.0
      - name: Install Node packages
        run: |
          npm install gulp
          npm install
      - name: Install docs packages
        run: ./_docs.sh depend
      - name: Build and test
        run: |
          gulp build
          npm test
      - name: Push build
        env:
          CERTBOTBOT_SSH_KEY: ${{ secrets.CERTBOTBOT_SSH_KEY }}
        if: ${{ github.event_name != 'pull_request' }}
        run: ./push-build.sh
  notify:
    # Only notify about failed builds, do not notify about failed builds for
    # PRs, and only notify about failed pushes to master.
    if: ${{ failure() && github.event_name != 'pull_request' && (github.event_name != 'push' || github.ref == 'refs/heads/master') }}
    needs: ci
    runs-on: ubuntu-20.04
    steps:
      - name: Write Mattermost Message
        run: |
          WORKFLOW_RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "{\"text\":\"** :warning: $GITHUB_REPOSITORY: Build failed :warning: ** | [(see details)]($WORKFLOW_RUN_URL) \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
